name: Submit Extension or Script
description: Submit an extension or script to the Keyer store
title: "[Submission] "
labels: []
body:
  - type: markdown
    attributes:
      value: |
        ## Submit to Keyer Store

        Please submit your extension or script by providing the repository URL.

  - type: dropdown
    id: type
    attributes:
      label: Type
      description: Select the type of submission
      options:
        - extension
        - script
    validations:
      required: true

  - type: input
    id: repo
    attributes:
      label: Repository URL
      description: "Provide the GitHub repository URL"
      placeholder: "https://github.com/username/repo-name"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---

        **Supported formats**:
        - `https://github.com/owner/repository`
        - `owner/repository`

        **Example**: `https://github.com/keyer/clipboard-history`

        **Note for Extensions**: Make sure your repository has at least one release tag. The workflow will fetch the package.json from the latest tag.
